[package]
name = "tamus"
version = "0.0.0"
description = "An app records your usage time"
authors = ["saicem"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.6", features = ["system-tray", "window-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows = { version = "0.56.0", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Accessibility",
    "Win32_System_SystemServices",
    "Win32_System_LibraryLoader",
    "Win32_Storage_FileSystem",
] }
window-shadows = "0.2.2"
chrono = { version = "0.4.38" }
once_cell = { version = "1.19.0" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
